# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Calendar-Pataphysical
version:      0.03
version_from: lib/DateTime/Calendar/Pataphysical.pm
installdirs:  site
requires:
    DateTime::Duration:            0
    DateTime::Locale:              0
    Params::Validate:              0.52

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
