---
abstract: 'Dates in the pataphysical calendar'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  DateTime: '0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DateTime-Calendar-Pataphysical
requires:
  DateTime::Duration: '0'
  DateTime::Locale: '0'
  Params::Validate: '0.52'
  constant: '0'
  overload: '0'
  perl: '5.006'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DateTime-Calendar-Pataphysical
  repository: http://github.com/book/DateTime-Calendar-Pataphysical.git
version: '0.05'
